<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="ISOCodex.Countries" Version="1.1.1" />
    <PackageReference Include="ISOCodex.Addressing" Version="2.1.1" />
    <PackageReference Include="ISOCodex.Addressing.Spain" Version="2.1.1" />
    <PackageReference Include="ISOCodex.Addressing.France" Version="2.1.1" />
    <PackageReference Include="ISOCodex.Addressing.Ireland" Version="2.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
